### ISSUE TITLE
Error running the UC2 implementation for Ryu

### ISSUE THREAD

**Issue by doriguzzi** [fp7-netide/Usecases#3]
The pingall works but after a while I get the following error messages :

![image](https://cloud.githubusercontent.com/assets/1794129/17002697/d88c4476-4ecc-11e6-8163-6c1e11d50713.png)

I'm using Ryu 4.4, no Network Engine, just Ryu and the Mininet script.

--rob

**Comment by Juanma-Sanchez** [comment]
Hello @doriguzzi ,

I have changed the code a little bit because it wasn't working with ryu 4.4 for me, and now I can't replicate this error.

¿Could you try the latest version and tell if you still get the same messages?
